title: Greenborough Writing
description: 

collections:
  characters:
    output: true
    permalink: /characters/:name/

defaults:
  - scope:
      path: ""
      type: "characters"
    values:
      layout: character
